### ISSUE TITLE
DaggerCoffeeComponent 는 어디서 정의하는건가요...?

### ISSUE THREAD

**Issue by yooncheolkim** [chihacker/dagger2SimpleExample#2]
https://github.com/chihacker/dagger2SimpleExample/blob/6660418c5fa5354aa8aada68dad53fe81a36f870/src/main/java/CoffeeApp.java#L43

**Comment by inkp80** [comment]
Dagger 접두사가 붙은 것은 Dagger가 생성하는 파일입니다.

@Component 어노테이션을 달아두었던 interface 또는 abstract 클래스가 Dagger라는 접두사가 붙어 Dagger에 의해 생성되게 됩니다.

```
@Component(modules = CoffeeMakerModule.class)
public interface CoffeeComponent {

    //provision method
    CoffeeMaker make();

    //member-injection method
    void inject(CoffeeMaker coffeeMaker);

}
```

예제 코드를 작성하신 후에 컴파일하면 CoffeeComponent를 implement하여 생성한 DaggerCoffeeComponent를 검색할 수 있습니다.
